
#
# Makefile for javax.usb Windows implementation
#
# Copyright (c) 2003 Dan Streetman (ddstreet@ieee.org)
# Copyright (c) 2003 International Business Machines Corporation
# All Rights Reserved.
#
# This software is provided and licensed under the terms and conditions
# of the Common Public License:
# http://oss.software.ibm.com/developerworks/opensource/CPLv1.0.htm
#

!include $(NTMAKEENV)\makefile.def

